BookApp/Controllers/EventController.cs
using BookApp.Models;
using Microsoft.AspNetCore.Mvc;
using Shared;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BookApp.Helper;
using Microsoft.AspNetCore.Http;
using Services.Interface;
using Microsoft.AspNetCore.Authorization;

namespace BookApp.Controllers
{
    public class EventController : Controller
    {
        private readonly IEventBL _eventBl;

        public EventController(IEventBL eventBL)
        {
            _eventBl = eventBL;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult CreateEvent()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CreateEvent(EventModel userEvent)
        {
             Event evt = new EventModelToEventHelper().EventModelToEventMapping(userEvent);
            if (ModelState.IsValid)
            {
                evt.UserId = HttpContext.Session.GetString("username"); 

               

                if (_eventBl.CreateEvent(evt))
                     return RedirectToAction("Index", "Home");


            }
            //ViewBag.Message = "Some Problem Occured while creating the event";
            return View();
            
        }
        public IActionResult AllEvents()
        {
            IEnumerable<Event> events = _eventBl.GetAllEvent();

            return View(new EventToEventModelHelper().GetEventModels(events));

        }

        public IActionResult MyEvents()
        {
            string UserName = HttpContext.Session.GetString("username");
            var myEvents = _eventBl.GetMyEvents(UserName);
            return View(new EventToEventModelHelper().GetEventModels(myEvents));
        }


        public IActionResult EventsInvitedTo()
        {
            string UserEmail = HttpContext.Session.GetString("userEmail");
            var invitedEvents = _eventBl.GetInvitedTo(UserEmail);
            return View(new EventToEventModelHelper().GetEventModels(invitedEvents));
        }
        

        [HttpGet]
        public IActionResult EditEvent(int eventId)
        {
            EventModel model = new EventToEventModelHelper().EventToEventModelMapping(_eventBl.GetAnEvent(eventId));
            return View(model);
        }

        [HttpPost]
        public IActionResult EditEvent(EventModel eventModel)
        {
            if (ModelState.IsValid)
            {
                var evt = new EventModelToEventHelper().EventModelToEventMapping(eventModel);
                evt.EventId =eventModel.EventId;
                evt.UserId= HttpContext.Session.GetString("username");

                var test= _eventBl.EditEvent(evt);

                if (test)
                {
                    return RedirectToAction("MyEvents");
                }
                return RedirectToAction("ViewEvent", new { eventModel.EventId });
            }
            else
                return View();

        }

        public IActionResult ViewEvent(int eventId)
        {
            EventModel eventModel = new EventToEventModelHelper().EventToEventModelMapping(_eventBl.GetAnEvent(eventId));
            return View(eventModel);
        }

    }
}

BookApp/Controllers/LoginController.cs
using BookApp.Helper;
using BookApp.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Services.Interface;
using Shared;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BookApp.Controllers
{
    public class LoginController : Controller
    {
        private readonly IUserBL _userBl;

        public LoginController(IUserBL userBl)
        {
            _userBl = userBl;
        }
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Login(UserModel Loguser)
        {
            User user = new UserModelToUserHelper().UserModelToUserMapping(Loguser);

            if ( _userBl.UserExists(user))
            {
               var userEmail= _userBl.GetEmail(user);
                HttpContext.Session.SetString("username", user.UserName);
                HttpContext.Session.SetString("userEmail", userEmail);

                return RedirectToAction("index", "Home");

            }
            else
            {
                ViewBag.Message = "Invalid UserName or Password";
                return View();
            }
        }

        [HttpGet]
        public IActionResult Logout()
        {
            HttpContext.Session.Remove("username");
            HttpContext.Session.Remove("userEmail");
            return RedirectToAction("Index", "Home");
        }

    }
}

BookApp/Controllers/RegisterController.cs
using BookApp.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Shared;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BookApp.Helper;
using Services;
using Services.Interface;

namespace BookApp.Controllers
{
    public class RegisterController : Controller
    {
        private readonly IUserBL _userBl;

        public RegisterController(IUserBL userBl)
        {
            _userBl = userBl;
        }

        public ActionResult Index()
        {
            return View();
        }

        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Register(RegisterUserModel regUser)
        {

                User user = new RegisterUserModelToUserHelper().RegisterUserModelToUserMapping(regUser);
                if (ModelState.IsValid)
                {
                  if(await _userBl.AddUser(user))
                    return RedirectToAction("Login", "Login");
                }
            ViewBag.Message = "UserName or EmailId already exist";
            return View();
            }
            
        }
}

BookApp/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http;
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BookApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BookApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" href="http://helpdesk.nagarro.com">Customer Support</a>
                        </li>

                        @if (Context.Session.GetString("username") != null)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Event" asp-action="CreateEvent">CreateEvent</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Event" asp-action="MyEvents">MyEvents</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Event" asp-action="EventsInvitedTo">EventsInvitedTo</a>
                            </li>

                            @if (Context.Session.GetString("userEmail") == "myadmin@bookevents.com")
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Event" asp-action="AllEvents">AllEvents</a>
                                </li>
                            }
                            <li class="nav-item  dropdown">
                                <a class="nav-link dropdown-toggle text-dark " href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    @Context.Session.GetString("username")
                                </a>
                                <div class="dropdown-menu bg-white" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item text-dark" asp-action="Logout" asp-controller="Login">Logout</a>
                                </div>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Login">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Register" asp-action="Register">Registration form</a>
                            </li>
                        }



                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>


    <footer class="border-top footer text-center">
        <div class="container-fluid">
            Book Reading App &copy; @DateTime.Now.Year <a asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>