BookApp/Controllers/EventController.cs
using BookApp.Models;
using Microsoft.AspNetCore.Mvc;
using Shared;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BookApp.Helper;
using Microsoft.AspNetCore.Http;
using Services.Interface;
using Microsoft.AspNetCore.Authorization;

namespace BookApp.Controllers
{
    public class EventController : Controller
    {
        private readonly IEventBL _eventBl;

        public EventController(IEventBL eventBL)
        {
            _eventBl = eventBL;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult CreateEvent()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CreateEvent(EventModel userEvent)
        {
             Event evt = new EventModelToEventHelper().EventModelToEventMapping(userEvent);
            if (ModelState.IsValid)
            {
                evt.UserId = HttpContext.Session.GetString("username"); 

               

                if (_eventBl.CreateEvent(evt))
                     return RedirectToAction("Index", "Home");


            }
            //ViewBag.Message = "Some Problem Occured while creating the event";
            return View();
            
        }
        public IActionResult AllEvents()
        {
            IEnumerable<Event> events = _eventBl.GetAllEvent();

            return View(new EventToEventModelHelper().GetEventModels(events));

        }

        public IActionResult MyEvents()
        {
            string UserName = HttpContext.Session.GetString("username");
            var myEvents = _eventBl.GetMyEvents(UserName);
            return View(new EventToEventModelHelper().GetEventModels(myEvents));
        }


        public IActionResult EventsInvitedTo()
        {
            string UserEmail = HttpContext.Session.GetString("userEmail");
            var invitedEvents = _eventBl.GetInvitedTo(UserEmail);
            return View(new EventToEventModelHelper().GetEventModels(invitedEvents));
        }
        

        [HttpGet]
        public IActionResult EditEvent(int eventId)
        {
            EventModel model = new EventToEventModelHelper().EventToEventModelMapping(_eventBl.GetAnEvent(eventId));
            return View(model);
        }

        [HttpPost]
        public IActionResult EditEvent(EventModel eventModel)
        {
            if (ModelState.IsValid)
            {
                var evt = new EventModelToEventHelper().EventModelToEventMapping(eventModel);
                evt.EventId =eventModel.EventId;
                evt.UserId= HttpContext.Session.GetString("username");

                var test= _eventBl.EditEvent(evt);

                if (test)
                {
                    return RedirectToAction("MyEvents");
                }
                return RedirectToAction("ViewEvent", new { eventModel.EventId });
            }
            else
                return View();

        }

        public IActionResult ViewEvent(int eventId)
        {
            EventModel eventModel = new EventToEventModelHelper().EventToEventModelMapping(_eventBl.GetAnEvent(eventId));
            return View(eventModel);
        }

    }
}

BookApp/Controllers/HomeController.cs
using BookApp.Helper;
using BookApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Services.Interface;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace BookApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IEventBL _eventBl;
        public HomeController(ILogger<HomeController> logger, IEventBL eventBL)
        {
            _logger = logger;
            _eventBl = eventBL;
        }

        public IActionResult Index()
        {
            var eventListMain = _eventBl.GetAllEvent();
            var evt = new EventToEventModelHelper().GetEventModels(eventListMain);
            return View(evt);
        }
        public IActionResult suc()
        {
            return View();
        }
        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

BookApp/Controllers/LoginController.cs
using BookApp.Helper;
using BookApp.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Services.Interface;
using Shared;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BookApp.Controllers
{
    public class LoginController : Controller
    {
        private readonly IUserBL _userBl;

        public LoginController(IUserBL userBl)
        {
            _userBl = userBl;
        }
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Login(UserModel Loguser)
        {
            User user = new UserModelToUserHelper().UserModelToUserMapping(Loguser);

            if ( _userBl.UserExists(user))
            {
               var userEmail= _userBl.GetEmail(user);
                HttpContext.Session.SetString("username", user.UserName);
                HttpContext.Session.SetString("userEmail", userEmail);

                return RedirectToAction("index", "Home");

            }
            else
            {
                ViewBag.Message = "Invalid UserName or Password";
                return View();
            }
        }

        [HttpGet]
        public IActionResult Logout()
        {
            HttpContext.Session.Remove("username");
            HttpContext.Session.Remove("userEmail");
            return RedirectToAction("Index", "Home");
        }

    }
}

BookApp/Views/Home/Index.cshtml
@using Microsoft.AspNetCore.Http;
@model IEnumerable<EventModel>

@{
    ViewData["Title"] = "Home Page";
}

<div class="container">
    <div class="text-center">
        <h1 class="display-4 text-primary font-weight-bold">Welcome!!</h1>
        <div class="row">
            <div class="col-md-6 ">
                <a class="btn btn-outline-primary"> <h4>Previous Events</h4></a>
                <div class="row">
                    @if (Context.Session.GetString("username") != null)
                    {
                        @foreach (var _event in Model)
                        {
                            @if (_event.Date < DateTime.Now && (_event.IsPrivate == false || (_event.UserId == Context.Session.GetString("username") && _event.IsPrivate == true)))
                            {
                                <div class="container">
                                    <div class="col py-2">
                                        <div class="p-2 border bg-light form-inline" style="justify-content:space-between">
                                            <h6 class="px-2">
                                                <a class="text-danger" href="@Url.Action("ViewEvent","Event",new {eventId=_event.EventId })">@_event.Title</a>
                                            </h6>
                                        </div>
                                    </div>
                                </div>

                            }
                        }
                    }
                    else
                    {
                        @foreach (var _event in Model)
                        {
                            @if (_event.Date < DateTime.Now && _event.IsPrivate == false)
                            {
                                <div class="container">
                                    <div class="col py-2">
                                        <div class="p-2 border bg-light form-inline" style="justify-content:space-between">
                                            <h6 class="px-2">
                                                <a class="text-danger" href="@Url.Action("ViewEvent","Event",new {eventId=_event.EventId })">@_event.Title</a>
                                            </h6>
                                        </div>
                                    </div>
                                </div>
                            }
                        }
                    }

                </div>

            </div>
            <div class="col-md-6 ">
                <a class="btn btn-outline-primary" ><h4>Upcoming Events</h4></a>
                <div class="row">
                    @if (Context.Session.GetString("username") != null)
                    {
                        @foreach (var _event in Model)
                        {
                            @if (_event.Date > DateTime.Now && (_event.IsPrivate == false || (_event.UserId == Context.Session.GetString("username") && _event.IsPrivate == true)))
                            {
                                <div class="container">
                                    <div class="col py-2">
                                        <div class="p-2 border bg-light form-inline" style="justify-content:space-between">
                                            <h6 class="px-2">
                                                <a class="text-danger" href="@Url.Action("ViewEvent","Event",new {eventId=_event.EventId })">@_event.Title</a>
                                            </h6>
                                        </div>
                                    </div>
                                </div>

                            }
                        }
                    }
                    else
                    {
                        @foreach (var _event in Model)
                        {

                            @if (_event.Date > DateTime.Now && _event.IsPrivate == false)
                            {
                                <div class="container">
                                    <div class="col py-2">
                                        <div class="p-2 border bg-light form-inline" style="justify-content:space-between">
                                            <h6 class="px-2">
                                                <a class="text-danger" href="@Url.Action("ViewEvent","Event",new {eventId=_event.EventId })">@_event.Title</a>
                                            </h6>
                                        </div>
                                    </div>
                                </div>
                            }
                        }
                    }
                </div>
            </div>
        </div>
    </div>
</div>

BookApp/Views/Home/suc.cshtml
@{
    ViewData["Title"] = "suc";
}
@using Microsoft.AspNetCore.Http;
<h1>suc</h1>
<div>
    Welcome @Context.Session.GetString("username")
    <a asp-controller="Login" asp-action="logout">Logout</a>
</div>